// ** import types
import type { AIFormData, FormField } from '@/types/extension'
import type { LLMProvider } from './constants'

// ** import constants
import { PROVIDERS, DEFAULT_PROVIDER, DEFAULT_MODELS, LLM_GENERATION_CONFIG } from './constants'

// ** import utils
import { buildPrompt, type ModelMetadata } from './prompt'
import { parseAIResponse } from './parser'

// ** Provider Settings Interface
interface ProviderSettings {
  provider: LLMProvider
  model: string
  apiKey: string
}

/**
 * Per-step timings returned alongside the parsed AI data so the
 * content script can log a detailed performance breakdown.
 */
export interface AIResult {
  data: AIFormData
  timings: {
    promptMs: number
    apiMs: number
    parseMs: number
  }
}

/** Maximum time we wait for any single AI provider response. */
const PROVIDER_TIMEOUT_MS = 30_000

/**
 * fetch() with a hard timeout. Aborts the request when the timeout
 * elapses so the UI never hangs on a slow or stuck provider.
 */
async function fetchWithTimeout(
  url: string,
  init: RequestInit,
  timeoutMs: number = PROVIDER_TIMEOUT_MS
): Promise<Response> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    return await fetch(url, { ...init, signal: controller.signal })
  } finally {
    clearTimeout(timer)
  }
}

function timeoutErrorMessage(): string {
  return 'AI request timed out. Please try again.'
}

async function getProviderSettings(): Promise<ProviderSettings> {
  const result = await chrome.storage.sync.get([
    'llmProvider', 'llmModel', 'llmApiKeys'
  ])
  const provider: LLMProvider = (result.llmProvider as LLMProvider) || DEFAULT_PROVIDER
  const apiKeys = (result.llmApiKeys as Record<string, string>) || {}
  const apiKey = apiKeys[provider]
  if (!apiKey) {
    throw new Error(`No API key found for ${PROVIDERS[provider].name}. Please configure it in settings.`)
  }
  const model = (result.llmModel as string) || DEFAULT_MODELS[provider]
  return { provider, model, apiKey }
}

async function callGeminiAPI(prompt: string, model: string, apiKey: string): Promise<string> {
  const url = `${PROVIDERS.gemini.baseUrl}/${model}:generateContent?key=${apiKey}`
  let response: Response
  try {
    response = await fetchWithTimeout(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
    })
  } catch (err) {
    if ((err as Error).name === 'AbortError') throw new Error(timeoutErrorMessage())
    throw err
  }
  if (!response.ok) {
    let message = `Gemini API error: ${response.status} ${response.statusText}`
    try {
      const data = await response.json()
      if (data.error?.message) message = data.error.message
    } catch { /* keep default */ }
    throw new Error(message)
  }
  const data = await response.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text
  if (!text) throw new Error('No content generated by Gemini AI')
  return text
}

async function callGroqAPI(prompt: string, model: string, apiKey: string): Promise<string> {
  const url = `${PROVIDERS.groq.baseUrl}/chat/completions`
  let response: Response
  try {
    response = await fetchWithTimeout(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: prompt }],
        temperature: LLM_GENERATION_CONFIG.temperature,
        max_tokens: LLM_GENERATION_CONFIG.maxTokens
      })
    })
  } catch (err) {
    if ((err as Error).name === 'AbortError') throw new Error(timeoutErrorMessage())
    throw err
  }
  if (!response.ok) {
    let message = `Groq API error: ${response.status} ${response.statusText}`
    try {
      const data = await response.json()
      if (data.error?.message) message = data.error.message
    } catch { /* keep default */ }
    throw new Error(message)
  }
  const data = await response.json()
  const text = data.choices?.[0]?.message?.content
  if (!text) throw new Error('No content generated by Groq AI')
  return text
}

async function callOpenRouterAPI(prompt: string, model: string, apiKey: string): Promise<string> {
  const url = `${PROVIDERS.openrouter.baseUrl}/chat/completions`
  let response: Response
  try {
    response = await fetchWithTimeout(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': 'https://github.com/jacksonkasi1/smartfill-extension',
        'X-Title': 'SmartFill Extension'
      },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: prompt }],
        temperature: LLM_GENERATION_CONFIG.temperature,
        max_tokens: LLM_GENERATION_CONFIG.maxTokens
      })
    })
  } catch (err) {
    if ((err as Error).name === 'AbortError') throw new Error(timeoutErrorMessage())
    throw err
  }
  if (!response.ok) {
    let message = `OpenRouter API error: ${response.status} ${response.statusText}`
    try {
      const data = await response.json()
      if (data.error?.message) message = data.error.message
    } catch { /* keep default */ }
    throw new Error(message)
  }
  const data = await response.json()
  const text = data.choices?.[0]?.message?.content
  if (!text) throw new Error('No content generated by OpenRouter AI')
  return text
}

/**
 * Generate form data using the configured LLM provider. Returns both
 * the parsed fields and per-step timings so the caller can show a
 * useful performance log.
 */
export async function generateFormData(
  fields: FormField[],
  customPrompt?: string
): Promise<AIResult> {
  const { provider, model, apiKey } = await getProviderSettings()

  const isRecommended = PROVIDERS[provider].models.some(m => m.id === model)
  const modelType: 'recommended' | 'custom' = isRecommended ? 'recommended' : 'custom'
  const modelMetadata: ModelMetadata = {
    provider: PROVIDERS[provider].name,
    modelId: model,
    modelType
  }

  // ---- Prompt build ----
  const t0 = performance.now()
  const prompt = buildPrompt(fields, customPrompt, modelMetadata)
  const promptMs = performance.now() - t0

  // ---- Provider call ----
  const t1 = performance.now()
  let generatedText: string
  switch (provider) {
    case 'gemini': generatedText = await callGeminiAPI(prompt, model, apiKey); break
    case 'groq': generatedText = await callGroqAPI(prompt, model, apiKey); break
    case 'openrouter': generatedText = await callOpenRouterAPI(prompt, model, apiKey); break
    default: throw new Error(`Unsupported provider: ${provider}`)
  }
  const apiMs = performance.now() - t1

  // ---- Parse ----
  const t2 = performance.now()
  const data = parseAIResponse(generatedText, fields, customPrompt)
  const parseMs = performance.now() - t2

  return {
    data,
    timings: { promptMs, apiMs, parseMs }
  }
}
